### ISSUE TITLE
No Print Option in the Paper Wallet window

### ISSUE THREAD

**Issue by ArcherBullseye** [swiftlettech/smart-sweeper#36]
Users need to hit Ctrl+P and that might be confusing for some.

**Comment by dantheman2865** [comment]
Can we just make it automatically print? A user can always close out of the print dialog if they don't want to print it.

**Comment by miyakoj** [comment]
It should automatically open a print dialog when the modal opens.

**Comment by ArcherBullseye** [comment]
May have been a local issue then.

**Comment by miyakoj** [comment]
The command was commented out from when I was working on the wallet layout. I also added more information about printing wallets to the help section.
