### ISSUE TITLE
Error when Sending

### ISSUE THREAD

**Issue by ArcherBullseye** [swiftlettech/smart-sweeper#41]
Getting error when sending.

Unhandled Error
TypeError: Cannot read property 'transactions' of undefined
    at C:/Users/David/AppData/Local/Programs/SmartSweeper/resources/app.asar/smartcashapi.js:173:97
    at Array.forEach (<anonymous>)
    at C:/Users/David/AppData/Local/Programs/SmartSweeper/resources/app.asar/smartcashapi.js:166:23
    at C:/Users/David/AppData/Local/Programs/SmartSweeper/resources/app.asar/rpc-client.js:112:13
    at C:/Users/David/AppData/Local/Programs/SmartSweeper/resources/app.asar/node_modules/node-smartcash/lib/index.js:38:8
    at C:/Users/David/AppData/Local/Programs/SmartSweeper/resources/app.asar/node_modules/node-smartcash/lib/jsonrpc.js:132:13
    at Array.forEach (<anonymous>)
    at IncomingMessage.<anonymous> (C:/Users/David/AppData/Local/Programs/SmartSweeper/resources/app.asar/node_modules/node-smartcash/lib/jsonrpc.js:121:15)

![image](https://user-images.githubusercontent.com/36517538/47793213-2a9f1600-dcf4-11e8-98eb-a56fb714c376.png)

**Comment by miyakoj** [comment]
Fixed in 235505e
